### ISSUE TITLE
Cloning repo asks for IBM login credentials

### ISSUE THREAD

**Issue by joelandman** [open-power-sdk/curt#50]
I'm not sure this was intended, but this appears to be the case.

> git clone https://github.ibm.com/sdk/curt.git
Cloning into 'curt'...
Username for 'https://github.ibm.com': 
Password for 'https://github.ibm.com': 
remote: Anonymous access denied
fatal: Authentication failed for 'https://github.ibm.com/sdk/curt.git/'

**Comment by ThinkOpenly** [comment]
Thank you for reporting this issue.  That's an oopsie.  I'll fix it here in a moment.
